CREATE DATABASE ppi;
USE ppi;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    idade VARCHAR(100) NOT NULL,
    cpf VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);